FROM denoland/deno:2.9.1 AS builder

WORKDIR /app

COPY v2/web/deno.json v2/web/deno.lock v2/web/package.json ./
RUN deno install --frozen

COPY v2/web ./
RUN deno task build

FROM nginx:1.27-alpine

COPY v2/deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/client /usr/share/nginx/html

EXPOSE 80
