// Review copies use the frontend renderer and explicit local inputs, not live API data.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { runInNewContext } from 'node:vm'
import { createServer } from 'vite'

const webRoot = new URL('../', import.meta.url)
const output = new URL('prompt-builder-previews/', webRoot)
const manifest = JSON.parse(
  readFileSync(new URL('../prompt-builders/manifest.json', webRoot), 'utf8'),
)
const server = await createServer({
  root: fileURLToPath(webRoot),
  configFile: false,
  server: { middlewareMode: true },
  appType: 'custom',
})
try {
  const { metaPromptFor } = await server.ssrLoadModule(
    '/src/lib/meta-prompt.ts',
  )
  const { scenarioModule } = await server.ssrLoadModule(
    '/src/scenarios/index.ts',
  )
  const inputs: Record<string, unknown> = {}
  const links: string[] = []
  mkdirSync(output, { recursive: true })
  for (const [id, entries] of Object.entries(manifest)) {
    const source = readFileSync(
      new URL(`../scenarios/scenarios/${id}/script.js`, webRoot),
      'utf8',
    )
    const meta = runInNewContext(`${source}\n;meta`, {}, { timeout: 1000 })
    const module = scenarioModule(id)
    inputs[id] = {
      title: meta.title,
      scoring: meta.scoring ?? null,
      promptUnitLimit: 1000,
    }
    for (
      const [key, entry] of Object.entries(
        entries as Record<string, { side: 'a' | 'b'; file: string }>,
      )
    ) {
      const role = module?.roles.find((role: { key: string }) =>
        role.key === key
      )
      const roleName = role?.name ??
        (entry.side === 'a' ? meta.sideAName : meta.sideBName)
      const text = metaPromptFor(
        module,
        meta.title,
        entry.side,
        roleName,
        meta.scoring,
        role?.key ?? null,
        1000,
      )
      const filename = `${id}-${key}.txt`
      writeFileSync(new URL(filename, output), text)
      links.push(
        `- [${id} / ${key}](${filename}) — product template: ${entry.file}`,
      )
    }
  }
  writeFileSync(
    new URL('inputs.json', output),
    JSON.stringify(inputs, null, 2) + '\n',
  )
  writeFileSync(
    new URL('README.md', output),
    [
      '# Prompt Builder review copies',
      '',
      'Generated by the frontend renderer from local scenario metadata and a 1000-unit example limit. These are not live API snapshots. inputs.json records these inputs; runtime reference material comes from the bundled asset. Each .txt contains only the text that would be copied for those inputs.',
      '',
      ...links,
      '',
    ].join('\n'),
  )
  console.log(
    `Rendered ${links.length} review copies in ${fileURLToPath(output)}`,
  )
} finally {
  await server.close()
}
