// Tonal synthesis only. Names describe the intended character, not recordings
// of physical instruments. Keep hover/click dynamics consistent across sets.
export const SOUND_PALETTES = [
  {
    id: 'clear',
    name: '清透轻点',
    description: '接近当前版，短、清楚、留白多。',
    pitch: 1,
    attack: 0.005,
    decay: 1,
    ratios: [1, 2, 3],
    levels: [1, 0.12, 0.025],
    bend: 0,
    spacing: 1,
    interval: 1,
  },
  {
    id: 'wood',
    name: '温润木琴',
    description: '偏低的圆润敲击，收尾很快。',
    pitch: 0.78,
    attack: 0.004,
    decay: 0.7,
    ratios: [1, 3, 6],
    levels: [1, 0.22, 0.035],
    bend: 0,
    spacing: 0.8,
    interval: 0.9,
  },
  {
    id: 'keys',
    name: '柔和电钢',
    description: '柔软起音，带一点温暖的和声。',
    pitch: 0.84,
    attack: 0.009,
    decay: 1.35,
    ratios: [1, 2, 3, 4],
    levels: [1, 0.34, 0.12, 0.04],
    bend: 0,
    spacing: 1.3,
    interval: 1.12,
  },
  {
    id: 'pluck',
    name: '轻巧拨弦',
    description: '起音利落、尾音轻，音符有弹性。',
    pitch: 1.08,
    attack: 0.004,
    decay: 0.85,
    ratios: [1, 2, 3, 4, 5],
    levels: [1, 0.4, 0.18, 0.08, 0.03],
    bend: 0,
    spacing: 0.72,
    interval: 1.12,
  },
  {
    id: 'drop',
    name: '圆润水滴',
    description: '音高轻轻下落，圆滑而轻快。',
    pitch: 1.12,
    attack: 0.006,
    decay: 1.1,
    ratios: [1, 2],
    levels: [1, 0.045],
    bend: 0.3,
    spacing: 1,
    interval: 1.25,
  },
  {
    id: 'bell',
    name: '小巧钟琴',
    description: '明亮的细小铃音，余韵更通透。',
    pitch: 1.3,
    attack: 0.007,
    decay: 1.45,
    ratios: [1, 2.76, 4],
    levels: [1, 0.12, 0.045],
    bend: 0,
    spacing: 1.2,
    interval: 1.12,
  },
  {
    id: 'low',
    name: '低音落键',
    description: '低一些、稳一些，点击更有分量。',
    pitch: 0.56,
    attack: 0.005,
    decay: 0.95,
    ratios: [1, 2, 3],
    levels: [1, 0.3, 0.08],
    bend: 0,
    spacing: 0.85,
    interval: 0.84,
  },
  {
    id: 'arcade',
    name: '明亮街机',
    description: '干净的电子音，短促上行、更活泼。',
    pitch: 1.16,
    attack: 0.004,
    decay: 0.75,
    ratios: [1, 3, 5],
    levels: [1, 0.24, 0.075],
    bend: 0,
    spacing: 0.58,
    interval: 1.5,
  },
  {
    id: 'music-box',
    name: '安静八音盒',
    description: '较高、较轻的音符，带一点童趣。',
    pitch: 1.65,
    attack: 0.008,
    decay: 1.15,
    ratios: [1, 2, 4],
    levels: [1, 0.18, 0.055],
    bend: 0,
    spacing: 1.45,
    interval: 0.9,
  },
  {
    id: 'warm',
    name: '暖调和弦',
    description: '柔和的三度叠音，完成时更有满足感。',
    pitch: 0.9,
    attack: 0.011,
    decay: 1.4,
    ratios: [1, 1.25, 1.5, 2],
    levels: [1, 0.24, 0.18, 0.04],
    bend: 0,
    spacing: 0.65,
    interval: 1.12,
  },
] as const

export type SoundPaletteID = typeof SOUND_PALETTES[number]['id']

export function soundPalette(id: unknown) {
  return SOUND_PALETTES.find((item) => item.id === id) ?? SOUND_PALETTES[0]
}
